#!/usr/bin/env bash

# Set up autograder files

cp /autograder/submission/sentences.py /autograder/source/sentences.py
cp /autograder/submission/reciprocal.py /autograder/source/reciprocal.py

cd /autograder/source
python3 run_tests.py
