#!/usr/bin/env bash

# Set up autograder files

cp /autograder/submission/collection.py /autograder/source/collection.py
cp /autograder/submission/textstats.py /autograder/source/textstats.py

cd /autograder/source
python3 run_tests.py
