#!/usr/bin/env bash

# Set up autograder files

cp /autograder/submission/checkout.py /autograder/source/checkout.py
cp /autograder/submission/manage.py /autograder/source/manage.py

cd /autograder/source
python3 run_tests.py
